export const localeText = {
    // for filter panel
    page: 'Page',
    more: 'Plus',
    to: 'à',
    of: 'de',
    next: 'prochain',
    last: 'dernier',
    first: 'premier',
    previous: 'précédent',
    loadingOoo: 'Loading...',

    // for set filter
    selectAll: 'Tout sélectionner',
    searchOoo: 'Chercher...',
    blanks: 'vide',

    // for number filter and text filter
    filterOoo: 'filtre...',
    applyFilter: 'Appliquer Filtre...',
    equals: 'égale',
    notEqual: 'non égale',

    // for number filter
    lessThan: 'moins que',
    greaterThan: 'plus que',
    lessThanOrEqual: 'moins ou égale que',
    greaterThanOrEqual: 'plus ou égale que',
    inRange: 'entre',

    // for text filter
    contains: 'contient',
    notContains: 'ne content pas',
    startsWith: 'commence par',
    endsWith: 'finit par',

    // filter conditions
    andCondition: 'et',
    orCondition: 'ou',

    // the header of the default group column
    group: 'groupe',

    // tool panel
    columns: 'colone',
    filters: 'filtres',
    rowGroupColumns: 'Colone de groupe',
    rowGroupColumnsEmptyMessage: 'Groupe Vide',
    valueColumns: 'Valeur colone',
    pivotMode: 'Mode Pivot',
    groups: 'Groupes',
    values: 'valeurs',
    pivots: 'pivots',
    valueColumnsEmptyMessage: 'Vide',
    pivotColumnsEmptyMessage: 'vide',
    toolPanelButton: 'Panneau de Configuration',

    // other
    noRowsToShow: 'Aucunes lignes',
    enabled: 'actionner',

    // enterprise menu
    pinColumn: 'figer la colone',
    valueAggregation: 'Valeur Agg',
    autosizeThiscolumn: 'dimension auto',
    autosizeAllColumns: 'dimension auto: toute',
    groupBy: 'Grouper par',
    ungroupBy: 'Dégrouper',
    resetColumns: 'réinitialiser colones',
    expandAll: 'toutes ouvrir',
    collapseAll: 'toutes fermer',
    toolPanel: 'Panneau de Configuration',
    export: 'Exporter',
    csvExport: 'format CSV',
    excelExport: 'format excel (.xlsx)',
    excelXmlExport: 'format excel (.xml)',

    // enterprise menu (charts)
    pivotChartAndPivotMode: 'Mode Pivot et Graphique',
    pivotChart: 'Graphe Pivot',
    chartRange: 'Selection Graphique',

    columnChart: 'Colone Graphique',
    groupedColumn: 'Colone Groupe',
    stackedColumn: 'Colone Empilée',
    normalizedColumn: 'Colone normalisée',

    barChart: 'Bar',
    groupedBar: 'Bars Groupées',
    stackedBar: 'Bars Empilées',
    normalizedBar: 'Bars Normalisées',

    pieChart: 'Camembert',
    pie: 'Camembert',
    doughnut: 'Doughnut',

    line: 'Ligne',

    xyChart: 'Nuage de Points',
    scatter: 'Nuage de Points',
    bubble: 'groupe de points',

    areaChart: 'Surface Graphique',
    area: 'Surface',
    stackedArea: 'Surfaces superposées',
    normalizedArea: 'Surfaces Normalisées',

    // enterprise menu pinning
    pinLeft: 'figée à gauche <<',
    pinRight: 'figée à droite >>',
    noPin: 'défigée <>',

    // enterprise menu aggregation and status bar
    sum: 'somme',
    min: 'Min',
    max: 'Max',
    none: 'Null',
    count: 'Compteur',
    average: 'Moyenne',
    filteredRows: 'lignes filtées',
    selectedRows: 'lignes sélectionées',
    TotalCols: 'total lignes',
    totalAndFilteredRows: 'total lignes filtrées',

    // standard menu
    copy: 'copier',
    copyWithHeaders: 'Copier avec entête',
    ctrlC: 'ctrl + C',
    paste: 'Coller',
    ctrlV: 'ctrl + V',

    // charts
    pivotChartTitle: 'laPivot Chart',
    rangeChartTitle: 'laRange Chart',
    settings: 'laSettings',
    data: 'données',
    format: 'format',
    categories: 'categories',
    series: 'series',
    xyValues: 'laX Y Values',
    paired: 'laPaired Mode',
    axis: 'laAxis',
    color: 'laColor',
    thickness: 'laThickness',
    xRotation: 'laX Rotation',
    yRotation: 'laY Rotation',
    ticks: 'laTicks',
    width: 'laWidth',
    length: 'laLength',
    padding: 'laPadding',
    chart: 'laChart',
    title: 'laTitle',
    background: 'laBackground',
    font: 'laFont',
    top: 'laTop',
    right: 'laRight',
    bottom: 'laBottom',
    left: 'laLeft',
    labels: 'laLabels',
    size: 'laSize',
    minSize: 'laMinimum Size',
    maxSize: 'laMaximum Size',
    legend: 'laLegend',
    position: 'laPosition',
    markerSize: 'laMarker Size',
    markerStroke: 'laMarker Stroke',
    markerPadding: 'laMarker Padding',
    itemPaddingX: 'laItem Padding X',
    itemPaddingY: 'laItem Padding Y',
    strokeWidth: 'laStroke Width',
    offset: 'laOffset',
    offsets: 'laOffsets',
    tooltips: 'laTooltips',
    callout: 'laCallout',
    markers: 'laMarkers',
    shadow: 'laShadow',
    blur: 'laBlur',
    xOffset: 'laX Offset',
    yOffset: 'laY Offset',
    lineWidth: 'laLine Width',
    normal: 'laNormal',
    bold: 'laBold',
    italic: 'laItalic',
    boldItalic: 'laBold Italic',
    predefined: 'laPredefined',
    fillOpacity: 'laFill Opacity',
    strokeOpacity: 'laLine Opacity',
    columnGroup: 'laColumn',
    barGroup: 'laBar',
    pieGroup: 'laPie',
    lineGroup: 'laLine',
    scatterGroup: 'laScatter',
    areaGroup: 'laArea',
    groupedColumnTooltip: 'laGrouped',
    stackedColumnTooltip: 'laStacked',
    normalizedColumnTooltip: 'la100% Stacked',
    groupedBarTooltip: 'laGrouped',
    stackedBarTooltip: 'laStacked',
    normalizedBarTooltip: 'la100% Stacked',
    pieTooltip: 'laPie',
    doughnutTooltip: 'laDoughnut',
    lineTooltip: 'laLine',
    groupedAreaTooltip: 'laGrouped',
    stackedAreaTooltip: 'laStacked',
    normalizedAreaTooltip: 'la100% Stacked',
    scatterTooltip: 'laScatter',
    bubbleTooltip: 'laBubble',
    noDataToChart: 'laNo data available to be charted.',
    pivotChartRequiresPivotMode: 'laPivot Chart requires Pivot Mode enabled.',
}